### ISSUE TITLE
When running Nebula with pip: FileNotFoundError: [Errno 2] No such file or directory: './unified_models'

### ISSUE THREAD

**Issue by DigeSegun** [berylliumsec/nebula#8]
https://github.com/berylliumsec/nebula/blob/472d3ba504c0de7cccfba4b100c63360ad7daed3/src/nebula.py#L123

At this line in the code I get a error when trying to run due to not having a file called unified models. Maybe It was supposed to get added through docker but I used the pip install way. Also as I stated in Jira Docker was not working

**Comment by berryliumsec** [comment]
@DigeSegun this issue has been fixed in this commit: https://github.com/berylliumsec/nebula/pull/9/commits/22fc03d7c5e89ae3427eadca9692f62dcddc827b
Please try again and close the issue if it has been fixed for you.

Dont forget to run `pip install nebula-ai --upgrade` to get the latest version and to pull a new docker image `docker pull berylliumsec/nebula:latest"

**Comment by DigeSegun** [comment]
resolved
